#!/usr/bin/zsh

repo=`git remote -v | grep -m 1 "(push)" | sed -e "s/.*github.com[:/]\(.*\)\.git.*/\1/"`
branch=`git name-rev --name-only HEAD`
echo "... creating pull request for branch \"$branch\" in \"$repo\""
xdg-open https://github.com/$repo/pull/new/$branch &>/dev/null &
